version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "5333:5333"
    depends_on:
      - postgres
      - strapi
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${secrets.POSTGRES_DB}
      POSTGRES_USER: ${secrets.POSTGRES_USER}
      POSTGRES_PORT: ${secrets.DATABASE_PORT}
      POSTGRES_PASSWORD: ${secrets.POSTGRES_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data

  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_NAME: ${secrets.POSTGRES_DB}
      DATABASE_PORT: ${secrets.DATABASE_PORT}
      DATABASE_USERNAME: ${secrets.POSTGRES_USER}
      DATABASE_PASSWORD: ${secrets.POSTGRES_PASSWORD}
    volumes:
      - ./strapi:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - postgres
