version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./postgres:/var/lib/postgresql/data

  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - /srv/app/node_modules
      - ./strapi:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - ./frontend:/usr/src/app
    ports:
      - "5333:3000"
    depends_on:
      - postgres
      - strapi
