version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "${FRONTEND_PORT:-5333}:5333"
    depends_on:
      - postgres
      - strapi
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./postgres:/var/lib/postgresql/data

  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_NAME: strapi
      DATABASE_PORT: ${POSTGRES_PORT}
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./strapi:/srv/app
    ports:
      - "${STRAPI_PORT:-1337}:1337"
    depends_on:
      - postgres
