version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PORT: "${DATABASE_PORT}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"
  strapi:
    build:
      context: ./strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: 0.0.0.0
      DATABASE_NAME: "${POSTGRES_DB}"
      DATABASE_PORT: "${DATABASE_PORT}"
      DATABASE_USERNAME: "${POSTGRES_USER}"
      DATABASE_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./strapi/api:/srv/app/api
      - ./strapi/config:/srv/app/config
      - ./strapi/extensions:/srv/app/extensions
      - ./strapi/public:/srv/app/public
    ports:
      - "${STRAPI_PORT}:1337"
    depends_on:
      - postgres

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /usr/src/app/node_modules
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - postgres
      - strapi
