version: "3"
services:
  postgres:
    image: postgres_prod
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PORT: "${DATABASE_PORT}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"

  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_NAME: "${POSTGRES_DB}"
      DATABASE_PORT: "${DATABASE_PORT}"
      DATABASE_USERNAME: "${POSTGRES_USER}"
      DATABASE_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - /srv/app/node_modules
      - ./strapi:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "5333:5333"
    depends_on:
      - postgres
      - strapi
