name: DIGITALOCEAN_DEPLOY

on:
  push:
    branches: [master]

jobs:
  Build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@master
      - name: Create .env
        run: |
          echo "STRAPI_PORT=$(cat ./.github/ports.json | json STRAPI_PORT)" > .env
          echo "POSTGRESS_PORT=$(cat ./.github/ports.json | json POSTGRESS_PORT)" > .env
          echo "FRONTEND_PORT=$(cat ./.github/ports.json | json FRONTEND_PORT)" > .env

      - name: Run build
        run: docker-compose up -d
