name: Manually triggered workflow
on:
  workflow_dispatch:
   inputs:
      logLevel:
        description: 'Date:'     
        required: false
jobs:
  Fetch_db:
    runs-on: [self-hosted, staging worker]
    steps:
      - run: |
          echo "Hello !"