name: Manually fetching data
on:
  workflow_dispatch:
   inputs:
      logLevel:
        description: 'Date:'     
        required: false
jobs:
  Fetch_db:
    runs-on: [self-hosted, staging worker]
    steps:
      - name: copy db
        run: cp -R /home/production/actions-runner/_prod/docker-meetfactory/docker-meetfactory/postgres /home/staging/actions-runner/_work/docker-meetfactory/docker-meetfactory 