name: PRODUCTION_DEPLOY

on:
  push:
    branches: [master]

jobs:
  Build:
    runs-on: [self-hosted, production worker]

    steps:
      - uses: actions/checkout@v2
        with:
          clean: false
      
      - name: Install linux json parser package
        run: npm install -g json

      - name: Create .env
        run: |
          echo "
          POSTGRES_DB=${{secrets.POSTGRES_DB}}  
          POSTGRES_USER=${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}}
          DATABASE_HOST=postgres_prod
          DATABASE_PORT=$(cat ./package.json | json PROD_POSTGRES)
          FRONTEND_PORT=$(cat ./package.json | json PROD_FRONTEND)
          STRAPI_PORT=$(cat ./package.json | json PROD_STRAPI)
          " > .env
      

      - name: Build containers
        run: docker-compose -f docker-compose-prod.yml build

      - name: Run build
        run: docker-compose -f docker-compose-prod.yml up -d