name: PRODUCTION_DEPLOY

on:
  push:
    branches: [master]

jobs:
  Build:
    runs-on: [self-hosted, production worker]

    steps:
      - uses: actions/checkout@v2
        with:
          clean: false
      
      - name: Install linux json parser package
        run: npm install -g json

      - name: Create .env
      #  run: echo "STAGING_PORT=$(cat ./.github/ports.json | json STAGING_PORT)" >> $GITHUB_ENV
        run: |
          echo "
          POSTGRES_DB=strapi 
          POSTGRES_USER=strapi
          POSTGRES_PASSWORD=strapi
          DATABASE_PORT=$(cat ./ports.json | json PROD_POSTGRES)
          FRONTEND_PORT=$(cat ./ports.json | json PROD_FRONTEND)
          STRAPI_PORT=$(cat ./ports.json | json PROD_STRAPI)
          " > .env
      

      - name: Build containers
        run: docker-compose -f docker-compose-prod.yml build

      - name: Run build
        run: docker-compose up -d