name: STAGING_DEPLOY

on:
  push:
    branches: [develop]

jobs:
  Build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@master
        with:
          clean: false
      - name: TEST
        run: |
          content=`cat ./ports.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"
          echo "${{fromJson(steps.set_var.outputs.packageJson).STAGING_POSTGRES}}"

      - name: Create .env
        run: |
          echo "
          POSTGRES_DB=strapi 
          POSTGRES_USER=strapi
          POSTGRES_PASSWORD=strapi
          DATABASE_PORT=${source ports.js | STAGING_POSTGRES}
          FRONTEND_PORT=${source ports.js | STAGING_FRONTEND}
          STRAPI_PORT=${source ports.js | STAGING_STRAPI}
          " > .env
      
      - name: Install frontend dependencies
        run: | 
          cd frontend
          yarn
      - name: Stop all the previous containers
        run: docker-compose down
      - name: Run build
        run: docker-compose up -d