name: STAGING_DEPLOY

on:
  push:
    branches: [develop]

jobs:
  Build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@master
        with:
          clean: false
      
      - name: Install linux json parser package
        run: npm install -g json

     
      - name: Install frontend dependencies
        run: | 
          cd frontend
          yarn
      - name: Stop all the previous containers
        run: docker-compose down
      - name: Run build
        run: docker-compose up -d