name: STAGING_DEPLOY

on:
  push:
    branches: [develop]

jobs:
  Build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@master
        with:
          clean: false
      - name: Where am i
        run: |
          ls
      - name: Create .env
        run: |
          echo "
          POSTGRES_DB=strapi 
          POSTGRES_USER=strapi
          POSTGRES_PASSWORD=strapi
          DATABASE_PORT=${source ports.js | STAGING_POSTGRES}
          FRONTEND_PORT=${source ports.js | STAGING_FRONTEND}
          STRAPI_PORT=${source ports.js | STAGING_STRAPI}
          " > .env
      
      - name: Install frontend dependencies
        run: | 
          cd frontend
          yarn
      - name: Stop all the previous containers
        run: docker-compose down
      - name: Run build
        run: docker-compose up -d