name: Test
on:
  workflow_dispatch:
   inputs:
      logLevel:
        description: 'Date:'     
        required: false
jobs:
  Fetch_db:
    runs-on: [self-hosted, staging worker]
    steps:
      - name: copy db
        run: |
          sudo docker exec -t ${{github.event.repository.name}}_postgres_prod_1 pg_dumpall -c -U strapi > /backup/dump.sql
          cat /backup/dump.sql | docker exec -i ${{github.event.repository.name}}_postgres_1 psql -U strapi

