name: Test
on:
  workflow_dispatch:
   inputs:
      logLevel:
        description: 'Date:'     
        required: false
jobs:
  Fetch_db:
    runs-on: [self-hosted, staging worker]
    steps:
      - name: copy db
        run: |
          ls | cat
          ls /backup/dump.sql | cat
          cd /
          ls | cat
          docker exec -i ${{github.event.repository.name}}_postgres_prod_1 -c "PGPASSWORD=strapi pg_dump --username strapi strapi" > /backup/dump.sql
          docker exec -i ${{github.event.repository.name}}_postgres_1 /bin/bash -c "PGPASSWORD=strapi psql --username strapi strapi" < /backup/dump.sql

